### ISSUE TITLE
Data import into Sahana Eden

### ISSUE THREAD

**Issue by chlarsen** [flavour/eden#1118]
Dear All,

Our group has huge issues importing data into Sahana Eden, even though we follow the prescribed templates religiously, using either .csv, .xls or .xlsx format. (The documentation is very unclear about the permitted file formats, and the patterns seem to shift: Sometimes, .csv import works, at other times it does not - on the same file! The same applies to .xls and .xlsx.)
Here is the output we get:
`````
Traceback (most recent call last):
  File "/home/web2py/gluon/restricted.py", line 227, in restricted
    exec ccode in environment
  File "applications/eden/compiled/controllers.hms.hospital.py", line 279, in <module>
  File "/home/web2py/gluon/globals.py", line 412, in <lambda>
    self._caller = lambda f: f()
  File "applications/eden/compiled/controllers.hms.hospital.py", line 256, in hospital
  File "applications/eden/compiled/models.00_utils.py", line 198, in s3_rest_controller
  File "applications/eden/modules/s3/s3rest.py", line 615, in __call__
    output = handler(self, **attr)
  File "applications/eden/modules/s3/s3rest.py", line 1679, in __call__
    output = self.apply_method(r, **attr)
  File "applications/eden/modules/s3/s3import.py", line 283, in apply_method
    output = self.generate_job(r, **attr)
  File "applications/eden/modules/s3/s3import.py", line 416, in generate_job
    commit_job = single_pass)
  File "applications/eden/modules/s3/s3import.py", line 999, in _generate_import_job
    **args)
  File "applications/eden/modules/s3/s3resource.py", line 2484, in import_xml
    extra_data=extra_data)
  File "applications/eden/modules/s3/s3xml.py", line 2322, in xls2tree
    on_demand=True)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 416, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/xlsx.py", line 791, in open_workbook_2007_xml
    x12sheet.process_stream(zflo, heading)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/xlsx.py", line 531, in own_process_stream
    self.do_dimension(elem)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/xlsx.py", line 565, in do_dimension
    rowx, colx = cell_name_to_rowx_colx(last_cell_ref)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/xlsx.py", line 89, in cell_name_to_rowx_colx
    assert 0 <= colx < X12_MAX_COLS
AssertionError
`````
And:
`````
In file: /home/web2py/applications/eden/compiled/controllers.hms.hospital.pyc
<code object <module> at 0x7f999dbb7730, file "applications/eden/compiled/controllers.hms.hospital.py", line 5>
`````
Any idea what is wrong?
Thanks a lot, indeed!

Chris

**Comment by flavour** [comment]
This would probably be better posted on the mailing list than put onto GitHub.

Personally I always import using CSV as the XLS/XLSX files are unwrapped to this format, hence can provide additional problems (e.g. XLSX requires a recent version of the xlrd library)
Also spreadsheet programs are notoroius for doing unexpected things to your data when trying to be 'helpful', so I look at the CSV file primarily through a text editor, only using a spreadsheet program when I really need the advantages it brings.

Trying to debug your specific issue is almost impossible without the file that you are trying to import.

**Comment by chlarsen** [comment]
Here is the .csv to be imported intpo the Hospital section:
`````
"Name","Code","Type","Status","Reopening Date","Power","Services","Beds Total","Beds Available","Organisation","Branch","Country","Building","Address","Postcode","L1","L2","L3","L4","Lat","Lon","Phone Switchboard","Phone Business","Phone Emergency","Email","Website","Fax","KV:XXX"
"Ngelehun",,"CHC",,,,,,,"Ministry of Health and Sanitation",,"Sierra Leone",,"Ngelehun, Badjia, Bo",,,,,,,,,,"+23211123456",,,,
"Njandama",,"MCHP",,,,,,,"Ministry of Health and Sanitation",,"Sierra Leone",,"Njandama, Badjia, Bo",,,,,,,,,,"+23211123456",,,,
`````
Anything obvious?
Thank you so much!
Chris

**Comment by flavour** [comment]
That file imports fine for me here.

NB I always use the 2-letter ISO code for country as smaller & less easy to typo/spell alternately (but this is OK too)

The Address would be better split into the L1, L2, L3 for Reporting & Mapping...

**Comment by flavour** [comment]
The error in the traceback you show above is in the xlsx handling of the xlrd library, so maybe try upgrading that library or using xls or csv

**Comment by chlarsen** [comment]
Following your advice, I am only using .csv, which is the smaller the preferred format anyway. What is happening now is that on any import attempt just nothing happens.
My gut feeling is that the server portion doing imports is hanging. Alas, I have in the current setting no way to play sys admin (but I believe they used Ubuntu), and may have to revert to my own dedicated server to check this out in more detail. It is, however, encouraging to know that you could actually handle the file. 
On my FreeBSD server, I plan to use daemontools to control the Web2Py instance - could this prevent such partial "hangs" , if my hunch is correct?
I will revert as soon as I have more information! Thanks a lot, and bests from Freetown.

**Comment by flavour** [comment]
I have no experience of Eden on freeBSD or using Web2Py with daemontools.

Our recommended installation guidelines are on the wiki. The one I use mostly is Cherokee/uWSGI but Apache/mod_WSGI is also in-use.

**Comment by nursix** [comment]
@chlarsen : as it looks your import .xslx has been modified using LibreOffice, and certain LibreOffice versions have a bug which do not properly encode the column range of the document, which then leads up to this crash in xlrd (as xlrd doesn't catch it).

LibreOffice won't fix the issue saying that their xslx output validates properly in Excel (hence it's not their problem), and python-xlrd has an open pull request to solve the problem https://github.com/python-excel/xlrd/pull/107

We can only hope that either side will solve it some day - and until then, you can only either use MS Excel to correct the output xslx (i.e. open it, and save it again), or use CSV format as Fran recommends. Very little else we can do from our side except to document it as a "known problem".

Sorry.

**Comment by nursix** [comment]
Note that the problem does not exist with .xls format (e.g. binary Excel format not XML), so if you use LibreOffice, you can save as .xls instead of .xlsx to work around the problem.

**Comment by nursix** [comment]
For the other problem re: "partial hangs" - could you elaborate on "just nothing happens"? Does the form actually get submitted (can you see the POST request go out in firebug)? Does the page remain the same or does it go blank? Can you open any other page in Sahana (e.g. navigating to another menu item)?

There is no known FreeBSD-specific problem with such symptoms, so before you reconfigure your server, I would recommend to first really exclude a client-side problem. Otherwise this could become really frustrating.

Btw - you did not yet mention which versions you are using (both web2py and Sahana). That is always very useful information when you report problems.

**Comment by nursix** [comment]
Oh sorry, I misread that - you say the current server is Ubuntu, and you are only planning to switch to FreeBSD.

However, the same strategy applies for Ubuntu - no known Ubuntu-specific problem that would cause the web server to "hang", and thus equally important to exclude client-side and transmission problems first.

As for daemontools - I don't see how that would help. Even if you would use supervise to control the web2py server process - the server process does obviously not /die/ but is either busy or waiting, and either situation would just indicate it as "running" - and hence supervise would do nothing.

If Sahana doesn't send a response to a request, then that does not mean it has died. It just means it either didn't receive the request, or processing the request takes so extraordinarily much time that it never produces a result that could be returned to the client. 

If it does send a response, but the response is either empty or wrong, then we do have a bug. But that situation can neither be caught with supervise.

So what we need to find out is: does Sahana receive the request, and does it really not respond or does it just look like it wouldn't respond. My suspicion is the latter: Sahana does receive the request, but responds by resending the import form instead of the import result, which looks in the UI as if nothing would happen.
