### ISSUE TITLE
problem with roles setting

### ISSUE THREAD

**Issue by ironista** [flavour/eden#1208]
I tried to create several roles in the Administration section, but it appears that the permissions are not properly applied. For example, when I create an user and associate to him a role with no CREATE permission on Organisation module and then log in with that user, I can still add new record to the Organisation resource.

I encountered this problem is in an old commit in November, and in the latest version.

**Comment by flavour** [comment]
I think you'll need to give a *lot* more information.
Consult the documentation for the different permutations of what is required for permissions:
http://eden.sahanafoundation.org/wiki/UserGuidelines/Admin/Permissions

**Comment by nursix** [comment]
That is the expected behaviour, yes.

The default configuration applies single-tier authorization (i.e. whether the user is logged-in or not logged-in), no roles or permission rules are applied. Anonymous users can read, authenticated users can write everything.

If you want to use role-based authorization, you must switch to a role-based security policy (3 or higher, in 000_config.py). For what you want to achieve, policy 5 is the recommended  setting.

**Comment by ironista** [comment]
I missed that page on the wiki, I'm sorry. Thank you guys :)
